# Generated by Django 4.0.1 on 2022-01-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
