# Generated by Django 2.0.7 on 2022-01-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220116_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='cart.OrderProduct'),
        ),
    ]
